Development:
  - permits:
      display_name: Building Permits
      socrata_id: but4-ky7y
      datetime_column: permit_issued
      location_column: site_location
      value_column: estimated_cost
      icon: wrench
      where: bld_permit_type not in ('Dismantle', 'Erection Of Signs')
      detail:
        Ticket Number: ticket_number
        Violation Code: violation_code
        Issuing Agency: agency_name
        Ticket Issued Date: ticket_issued_date
        Hearing Date: hearing_date
Sales:
  - side_lots:
      display_name: Side Lot Sales
      socrata_id: xxxx-xxxx
      datetime_column: sale_date
      location_column: location
      value_column: sale_amount
      icon: bank
      where:
      detail:
        Ticket Number: ticket_number
        Violation Code: violation_code
        Issuing Agency: agency_name
        Ticket Issued Date: ticket_issued_date
        Hearing Date: hearing_date
